services:
  postgres:
    build:
      context: ../postgres-jsonlog
    command:
      - postgres
      - -c
      - logging_collector=on
      - -c
      - log_destination=jsonlog
      - -c
      - log_directory=log
      - -c
      - log_filename=postgresql
      - -c
      - log_rotation_age=0
      - -c
      - log_rotation_size=0
      - -c
      - log_truncate_on_rotation=off
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: auth-database
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  auth-service:
    build:
      context: ..
      dockerfile: auth-service/Dockerfile
    ports:
      - "8081:8081"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
